In [1]:
# Robyn Baumann
# AST4762 Homework 3
# Sep 12, 2026


In [42]:
# import libraries needed for the program
import matplotlib.pyplot as plt
import numpy as np
import astropy.io.fits as fits
import hw3_rab_support_functions


In [43]:
dir(hw3_rab_support_functions)


['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'fits',
 'np',
 'os',
 'plt',
 'sp',
 'square']

In [30]:
# Begin Problem 2 
print("Problem 2:\n")

# create first test array for square and print
test_square_1 = np.arange(0,10)
print ('test_square_1 before square:', test_square_1, '\n' )

# square and print
test_square_1 = square(test_square_1)
print ('test_square_1 after square:', test_square_1, '\n' )

# second test for square and print:
test_square_2 = np.linspace(0,25,25).reshape(5,5)
print ('test_square_2 before square:', test_square_2, '\n' )

# square and print
test_square_2 = square(test_square_2)
print ('test_square_2 after square:', test_square_2, '\n' )


Problem 2:

test_square_1 before square: [0 1 2 3 4 5 6 7 8 9] 

test_square_1 after square: [ 0  1  4  9 16 25 36 49 64 81] 

test_square_2 before square: [[ 0.          1.04166667  2.08333333  3.125       4.16666667]
 [ 5.20833333  6.25        7.29166667  8.33333333  9.375     ]
 [10.41666667 11.45833333 12.5        13.54166667 14.58333333]
 [15.625      16.66666667 17.70833333 18.75       19.79166667]
 [20.83333333 21.875      22.91666667 23.95833333 25.        ]] 

test_square_2 after square: [[  0.           1.08506944   4.34027778   9.765625    17.36111111]
 [ 27.12673611  39.0625      53.16840278  69.44444444  87.890625  ]
 [108.50694444 131.29340278 156.25       183.37673611 212.67361111]
 [244.140625   277.77777778 313.58506944 351.5625     391.71006944]
 [434.02777778 478.515625   525.17361111 574.00173611 625.        ]] 



In [ ]:
# Begin Problem 3:
print('Problem 3:\n')

# create test


